### PR TITLE
chore: replace withdrawal status cancelled with rejected

### LINKED ISSUE #203: Change Withdrawal Status Cancelled to Rejected
# Task Overview

To return the correct response when a withdrawal fails
Change the withdrawal status from Cancelled to Rejected

# Dependencies

vegaprotocol/vega#4545

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #203

### CODE REVIEW

**Review by pscott31 — COMMENTED** [review]
Are all these formatting changes intentional? I don't have any particular problem with them, (though they seem rather arbitrary) it's just a little tricky to see what has functionally changed :)

**Comment by wwestgarth** [comment]
Second what Phil said about formatting changes. If its your editor thats capping lines lengths at 70 you'll want to up it.

**Comment by guoguojin** [comment]
No, they were auto-generated when I ran the generate script. The only change I made was to the vega.proto file, then ran `make protos`, all the swagger files were auto-generated

**Comment by wwestgarth** [comment]
> No, they were auto-generated when I ran the generate script. The only change I made was to the vega.proto file, then ran `make protos`, all the swagger files were auto-generated

All of the comments in the proto file have changed. Likely automatically by your editor. These are then propagated down into the swagger json.

> No, they were auto-generated when I ran the generate script. The only change I made was to the vega.proto file, then ran `make protos`, all the swagger files were auto-generated

This is not the case since `vega.proto`, the file you've changed, is full of formatting changes to the comments on the proto defitinions, likely done automatically by your editor.

**Comment by guoguojin** [comment]
Sorry about that, I misunderstood the issue. Don't know why Code was reformatting all the lines when the file was saved, must have been one of the plugins, but I don't know which one caused the problem. Anyway, corrected, in https://github.com/vegaprotocol/protos/pull/202/commits/63fcf6d9f1040a0ad51afa19ef6d5b4a2b1c7785

**Pull request merged**
